import { styled, ThemeProvider } from "@mui/material"
import Sidebar from "./components/sidebar"
import theme from "./styles/theme"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head></head>
            <body>
                <ThemeProvider theme={theme}>
                    <Sidebar />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    )
}